#!/bin/bash

# === Help panel === #
if [ "$1" == "help" ]; then
    echo "Available commands:"
    echo -e "\thelp: show this message and exits."
    echo -e "\tclean: cleans the work tree and exits."
    echo "If neither of these commands are passed, it will prepare the work tree to begin the build process"
    exit 0
fi

# === Clean workflow === #
if [ "$1" == "clean" ]; then
    cat .gitignore | grep -v '#' | xargs rm -rf
    exit 0
fi

# === Normal workflow === #
aclocal
autoheader
autoconf
automake --gnu --add-missing
exit 0
