#!/bin/bash

# === Help panel === #
if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
    echo ""
    exit 0
fi

# === Clean workflow === #
if [ "$1" == "clean" ]; then
    cat .gitignore | grep -v '#' | xargs rm -rf
    exit 0
fi

# === Normal workflow === #
aclocal
autoheader
autoconf
automake --gnu --add-missing
exit 0
